import test from 'node:test';
import assert from 'node:assert/strict';
import {CATALOG,WEAPONS,SPECIALS,PARTS,STAGES} from '../src/data.js';
import {REGIONS,pack,connected,randomShape,validateGrid,canonicalShape,findPlacement} from '../src/grid.js';
import {defaultConfig,aggregate,cost,validateTeam,clone} from '../src/customize.js';
import {generateRewards,rewardCounts} from '../src/rewards.js';
import {Battle,damageValue,lineClear} from '../src/sim.js';
const get=id=>CATALOG[id];
function rng(seed=42){return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
function battle(options={}){const a=defaultConfig(),e=defaultConfig(0,true);return new Battle({allies:[a],enemies:[e],setup:{allies:1,enemies:1,player:0,stage:'flat',duration:180,coordination:'spread'},getItem:get,rng:()=>.99,...options});}
test('Lメイン46とMGサブ48の合計94、全19武器と76技',()=>{assert.equal(REGIONS.main.cells.length,46);assert.equal(Object.values(REGIONS).reduce((s,r)=>s+r.cells.length,0),94);assert.equal(Object.keys(WEAPONS).length,19);assert.equal(Object.keys(SPECIALS).length,76);});
test('基本構成と複数モーター・特大電池構成が実際に配置できる',()=>{for(const ids of [['cpu:general','memory:standard','motor:standard','battery:standard'],['cpu:general','memory:standard','motor:standard','motor:standard','battery:standard'],['cpu:general','memory:standard','motor:high','battery:huge']]){const p=pack(ids.map(get));assert.ok(p);assert.deepEqual(validateGrid(p,get),[]);}});
test('ドロップ形状は辺でつながり、面積が変わらず単独Lへ入る',()=>{const random=rng();for(const size of [4,6,8,12])for(let i=0;i<40;i++){const shape=randomShape(size,random);assert.equal(shape.length,size);assert.ok(connected(shape));assert.ok(findPlacement({category:'cpu',shape},[],get,'main'));assert.equal(canonicalShape(shape),canonicalShape(shape.map(([x,y])=>[-y,x])));}});
test('脚部で回数を決め、重い武器の減少と保護を適用する',()=>{const c=defaultConfig();assert.equal(aggregate(c,get).jumps,2);c.armor.legs='armor:wild:legs';assert.equal(aggregate(c,get).jumps,3);c.sets[0].item='weapon:hammer';assert.equal(aggregate(c,get).jumps,2);c.armor.legs='armor:brawler:legs';assert.equal(aggregate(c,get).jumps,2);c.armor.body='armor:strider:body';assert.equal(aggregate(c,get).jumps,2);});
test('待機武器を重量へ加えず、狙撃クリティカルは100%',()=>{const c=defaultConfig();const before=aggregate(c,get).weight;c.sets[1].item='weapon:bazooka';assert.equal(aggregate(c,get).weight,before);c.sets[1].item='weapon:sniper';c.sets[1].shield=null;assert.equal(aggregate(c,get,1).crit,1);assert.equal(damageValue(260,2,100,true),390);});
test('汎用大5個の軽減は移動60%、攻撃30%、自然な下限以外の上限なし',()=>{const c=defaultConfig();for(let i=0;i<5;i++)c.placements.push({item:'aux:generic:2'});const s=aggregate(c,get);assert.ok(Math.abs(cost(s,'groundDash',18)-7.2)<1e-8);assert.ok(Math.abs(cost(s,'attack',44)-30.8)<1e-8);s.attackCut=2;assert.equal(cost(s,'attack',44),0);});
test('報酬は敵数で14/18/22、入手アップ3機で88、練習は0',()=>{for(const [kills,total]of [[1,14],[2,18],[3,22]])assert.equal(rewardCounts(kills,true).total,total);assert.equal(rewardCounts(3,true,3).total,88);const items=generateRewards({defeated:[{level:2},{level:2},{level:2}],won:true,collectors:3,level:2},rng());assert.equal(items.length,88);assert.equal(items.filter(i=>['cpu','memory','motor','battery','aux'].includes(i.category)).length,60);assert.equal(generateRewards({training:true}).length,0);});
test('ドロップ品1個を2機に使うと所持不足、基本品は自由',()=>{const a=defaultConfig(),b=defaultConfig();const item={...CATALOG['weapon:sword'],id:'loot:test',basic:false};a.sets[0].item=item.id;b.sets[0].item=item.id;const errors=validateTeam([a,b],[{item,count:1}]);assert.ok(errors.some(e=>e.includes('必要2個／所持1個')));assert.deepEqual(validateTeam([defaultConfig(),defaultConfig()],[]),[]);});
test('ポーズ中は全時間が止まり、BP0でも攻撃と既存Cを使える',()=>{const b=battle();b.countdown=0;b.paused=true;const snapshot=JSON.stringify(b.entities.map(u=>({bp:u.bp,c:u.c,t:u.tension})));b.tick(.04,{x:1,attack:true});assert.equal(b.time,0);assert.equal(JSON.stringify(b.entities.map(u=>({bp:u.bp,c:u.c,t:u.tension}))),snapshot);b.paused=false;const u=b.human;u.bp=0;u.c=500;assert.ok(b.useSkill(u,'sword:buff'));assert.equal(u.c,300);});
test('同じ武器を両セットへ登録しても残弾と再使用待ちがリセットされない',()=>{const c=defaultConfig();c.sets[0].item='weapon:pistol';c.sets[1].item='weapon:pistol';const b=battle({allies:[c]});b.countdown=0;const u=b.human;b.attack(u);const rt=b.runtime(u);assert.equal(rt.ammo,11);u.actionTime=0;b.switchWeapon(u);for(let i=0;i<8;i++)b.tick(.04);assert.equal(u.active,1);assert.equal(b.runtime(u),rt);assert.equal(rt.ammo,11);});
test('武器切替で使用済みの空中ジャンプを補充しない',()=>{const c=defaultConfig();c.sets[1].item='weapon:hammer';c.sets[1].shield=null;const b=battle({allies:[c]});b.countdown=0;const u=b.human;assert.ok(b.jump(u));assert.equal(u.jumpsUsed,1);u.active=1;b.refreshStats(u);assert.equal(b.jump(u),false);u.active=0;b.refreshStats(u);assert.ok(b.jump(u));assert.equal(u.jumpsUsed,2);assert.equal(b.jump(u),false);});
test('壁は弾道と爆風を遮り、表面から壁の裏にも通らない',()=>{const stage={obstacles:[{x:0,z:0,w:2,d:2,h:3}],ramps:[]};assert.equal(lineClear(stage,{x:-2,y:1,z:0},{x:2,y:1,z:0}),false);assert.equal(lineClear(stage,{x:-1,y:1,z:0},{x:2,y:1,z:0}),false);assert.equal(lineClear(stage,{x:-1,y:1,z:0},{x:-3,y:1,z:0}),true);});
test('全9人数構成で開始でき、初期資源と編成が成立する',()=>{for(let a=1;a<=3;a++)for(let e=1;e<=3;e++){const b=battle({allies:Array.from({length:a},(_,i)=>defaultConfig(i)),enemies:Array.from({length:e},(_,i)=>defaultConfig(i,true)),setup:{allies:a,enemies:e,stage:'yard',player:0,duration:180,coordination:'spread'}});assert.equal(b.entities.length,a+e);assert.equal(b.human.c,0);assert.equal(b.human.tension,100);}});
