const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{const server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:'inherit'});let browser;
try{
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:4173')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});fs.mkdirSync('charge-artifacts',{recursive:true});const errors=[];
 const game=await browser.newPage({viewport:{width:1100,height:800},recordVideo:{dir:'charge-artifacts',size:{width:1100,height:800}}});game.on('pageerror',e=>errors.push(e.message));
 await game.goto('http://127.0.0.1:4173');await game.locator('.home-copy').waitFor();await game.bringToFront();
 await game.evaluate(async()=>{const [{app},{defaultConfig}]=await Promise.all([import('/src/main.js'),import('/src/customize.js')]);app.state.units[0]=defaultConfig();app.state.enemies[0]=defaultConfig();Object.assign(app.state.setup,{allies:1,enemies:1,stage:'flat',duration:0,player:0,training:true});});
 await game.mouse.move(500,300);
 // Default W + attack, backward input, and full-charge W + release use actual
 // keyboard/mouse events and the game's fixed-step loop, not direct attacks.
 const resetApproach=async()=>game.evaluate(async()=>{const {app}=await import('/src/main.js');app.startBattle();const b=app.battle;b.countdown=0;b.training.freezeAI=true;b.training.infinite=true;b.rng=()=>.99;const u=b.human,v=b.entities[1];Object.assign(u,{x:0,z:0,yaw:0,target:v.id});Object.assign(v,{x:0,z:2.6,yaw:Math.PI,lp:10000});app.renderer.cameraYaw=0;app.renderer.manualYaw=0;const attack=b.attack.bind(b);window.approachStarts=[];window.approachInputs=[];b.attack=(unit,charge=0,input={})=>{const ok=attack(unit,charge,input);if(ok&&unit===u){window.approachStarts.push({charge,approach:!!u.attack?.approach});window.approachInputs.push({input,keys:[...app.controls.keys],yaw:u.yaw,camera:app.renderer.cameraYaw,focus:document.activeElement.tagName});}return ok;};});
 // Establish pointer lock before resetting the test duel; Chromium emits a
 // cursor-centering mousemove when lock starts, which can turn the camera.
 await resetApproach();await game.mouse.click(500,300);await game.waitForFunction(()=>!!document.pointerLockElement);await game.keyboard.press('KeyR');await game.waitForFunction(async()=>Math.abs((await import('/src/main.js')).app.renderer.cameraYaw)<.1);
 for(const key of ['KeyW','KeyS']){await resetApproach();await game.mouse.down();await game.keyboard.down(key);await game.waitForFunction(async()=>(await import('/src/main.js')).app.battle.human.charging);await game.mouse.up();await game.waitForFunction(()=>window.approachStarts.length===1);await game.keyboard.up(key);assert.equal(await game.evaluate(()=>window.approachStarts[0].approach),key==='KeyW',JSON.stringify(await game.evaluate(()=>window.approachInputs)));await game.waitForFunction(async()=>!(await import('/src/main.js')).app.battle.human.attack);if(key==='KeyW')assert(await game.evaluate(async()=>{const {app}=await import('/src/main.js');return app.battle.human.z>1&&app.battle.human.dealt>0&&app.battle.human.z<=app.battle.entities[1].z-.61;}));}
 await resetApproach();await game.mouse.down();await game.locator('.charge-display[data-charge-ready="true"]').waitFor();await game.keyboard.down('KeyW');await game.mouse.up();await game.waitForFunction(()=>window.approachStarts.length===1);await game.keyboard.up('KeyW');assert.deepEqual(await game.evaluate(()=>window.approachStarts[0]),{charge:1,approach:true});await game.waitForFunction(async()=>!(await import('/src/main.js')).app.battle.human.attack);assert(await game.evaluate(async()=>{const {app}=await import('/src/main.js');return app.battle.human.z>1&&app.battle.human.dealt>0;}));await game.screenshot({path:'charge-artifacts/approach-game.png'});
 assert.deepEqual(errors,[]);const video=game.video();await game.close();await video.saveAs('charge-artifacts/approach-input.webm');console.log('Approach browser passed: real W + attack, backward input, full-charge W + release, stop and hit.');
}catch(e){console.error(e);if(browser)for(const p of browser.contexts().flatMap(c=>c.pages())){console.error('Page state:',await p.locator('body').innerText().catch(()=>''));await p.screenshot({path:'charge-artifacts/approach-input-failure.png'}).catch(()=>{});}process.exitCode=1;}finally{await browser?.close();server.kill();}})();
