const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{const server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:'inherit'});let browser;
try{
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:4173')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1100,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('charge-artifacts',{recursive:true});
 await page.goto('http://127.0.0.1:4173');await page.locator('.home-copy').waitFor();
 await page.evaluate(async()=>{const [{app},{defaultConfig}]=await Promise.all([import('/src/main.js'),import('/src/customize.js')]);window.appUnderTest=app;app.state.units[0]=defaultConfig();app.state.enemies[0]=defaultConfig(0,true);app.state.enemies[1]=defaultConfig(1,true);for(const c of [app.state.units[0],app.state.enemies[0],app.state.enemies[1]]){c.passives=[];c.abilities=[];c.sets[0]={item:'weapon:sword',shield:null};}Object.assign(app.state.setup,{allies:1,enemies:2,stage:'flat',duration:0,player:0,training:true});});
 const cuts=[];
 for(let stage=0;stage<4;stage++){
  const result=await page.evaluate(async stage=>{
   const app=window.appUnderTest;app.startBattle();const b=app.battle;b.countdown=0;b.paused=true;b.rng=()=>.99;b.training.freezeAI=true;b.training.infinite=true;
   const [u,v,other]=b.entities;Object.assign(u,{x:0,z:0,yaw:0,lp:10000});Object.assign(v,{x:10,z:-10,lp:10000});Object.assign(other,{x:10,z:10,lp:10000});
   // Reach each cut through real hits on another opponent. Only the displayed
   // cut touches v, so the final-cut-only stagger rule remains observable.
   for(let i=0;i<stage;i++){Object.assign(other,{x:u.x,z:u.z+.8});u.target=other.id;if(!b.attack(u)||u.attack.combo!==i)throw Error('Hit-gated cut could not start');b.meleeStep(u,u.attack.duration*.9);b.paused=false;for(let j=0;j<100&&(u.attack||b.runtime(u).cooldown>0||u.actionTime>0);j++)b.tick(1/60);b.paused=true;}
   Object.assign(other,{x:10,z:10});Object.assign(v,{x:u.x,z:u.z+.8,yaw:Math.PI,target:u.id});u.target=v.id;b.attack(v);v.queuedAttack={charge:0,remaining:.2};const before=v.attack;if(!b.attack(u)||u.attack.combo!==stage)throw Error('Wrong displayed cut');b.meleeStep(u,u.attack.duration*.9);
   if(stage===3){for(let i=0;i<7;i++)b.updateUnit(v,{},1/60);}else v.hitReaction.elapsed=v.hitReaction.duration*.5;app.renderer.cameraYaw=-.75;app.renderer.manualYaw=-.75;app.renderer.camera.fov=30;app.renderer.camera.updateProjectionMatrix();app.renderer.render(b,1/60,b.time);const {Vector3}=await import('/vendor/three.module.min.js'),ref=app.renderer.robots.get(v.id);
   return {stage,dealt:u.dealt,interrupted:v.attack===null,kept:v.attack===before,kind:v.hitReaction.kind,queued:!!v.queuedAttack,stun:v.stun,down:v.down,phase:v.knockdown?.phase,height:v.y,up:new Vector3(0,1,0).applyQuaternion(ref.root.quaternion).y,fault:app.frameError};
  },stage);
  cuts.push(result);assert(result.dealt>0&&!result.fault,JSON.stringify(result));assert.equal(result.interrupted,stage===3);assert.equal(result.kind,stage===3?'stagger':'impact');assert.equal(result.down,0);if(stage===3){assert(Math.abs(result.up-1)<1e-8&&!result.queued&&result.stun>0&&result.height===0);assert.equal(result.phase,undefined);}else assert(result.kept&&result.queued&&result.stun===0);
  await page.screenshot({path:`charge-artifacts/stagger-sword-${stage+1}.png`});
 }
 // An actual connected four-cut sequence must still launch. No seeded hit ledger.
 const linked=await page.evaluate(async()=>{const app=window.appUnderTest;app.startBattle();const b=app.battle;b.countdown=0;b.paused=true;b.rng=()=>.99;b.training.freezeAI=true;b.training.infinite=true;const [u,v]=b.entities;Object.assign(u,{x:0,z:0,yaw:0,target:v.id,lp:10000});Object.assign(v,{x:0,z:.8,yaw:Math.PI,target:u.id,lp:10000});const damage=[];
  for(let stage=0;stage<3;stage++){const lp=v.lp;if(!b.attack(u))throw Error('Connected combo could not start');if(u.attack.combo!==stage)throw Error('Unexpected combo index');b.meleeStep(u,u.attack.duration*.9);damage.push(lp-v.lp);b.paused=false;for(let i=0;i<100&&(u.attack||b.runtime(u).cooldown>0||u.actionTime>0);i++)b.tick(1/60);b.paused=true;}
  if(!b.attack(v))throw Error('Victim could not attack');v.queuedAttack={charge:0,remaining:.2};const lp=v.lp;if(!b.attack(u)||u.attack.combo!==3)throw Error('Finishing cut could not start');b.meleeStep(u,u.attack.duration*.9);damage.push(lp-v.lp);for(let i=0;i<7;i++)b.updateUnit(v,{},1/60);app.renderer.cameraYaw=-.75;app.renderer.manualYaw=-.75;app.renderer.render(b,1/60,b.time);const {Vector3}=await import('/vendor/three.module.min.js'),ref=app.renderer.robots.get(v.id);return {damage,interrupted:v.attack===null,queued:!!v.queuedAttack,phase:v.knockdown?.phase,height:v.y,up:new Vector3(0,1,0).applyQuaternion(ref.root.quaternion).y,fault:app.frameError};});
 assert(linked.damage.every(d=>d>0)&&linked.interrupted&&!linked.queued&&linked.phase==='air'&&linked.height>0&&linked.up<.9&&!linked.fault,JSON.stringify(linked));await page.screenshot({path:'charge-artifacts/stagger-sword-connected.png'});
 const airborne=await page.evaluate(()=>{const b=window.appUnderTest.battle,[u,v]=b.entities,p={id:`review:${b.serial++}`,weapon:'sword',attackStats:u.stats,normal:true,coefficient:1,charge:0,finisher:true,exhausted:false,cPaid:new Set(),statusPaid:new Set(),freezeBoost:new Set()},before=JSON.stringify([v.knockdown,v.vy,v.y]),lp=v.lp;const damage=b.hit(u,v,p);window.downReview=[];const emit=b.event.bind(b);b.event=(type,data)=>{if(['down','rise','recovered'].includes(type))window.downReview.push({type,time:b.time});emit(type,data);};return {damage,lpChanged:v.lp<lp,unchanged:before===JSON.stringify([v.knockdown,v.vy,v.y])};});assert(airborne.damage>0&&airborne.lpChanged&&airborne.unchanged);
 const frozen=await page.evaluate(()=>{const b=window.appUnderTest.battle,v=b.entities[1];return JSON.stringify([b.time,v.knockdown,v.x,v.y,v.z]);});await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>{const b=window.appUnderTest.battle,v=b.entities[1];return JSON.stringify([b.time,v.knockdown,v.x,v.y,v.z]);}),frozen);
 await page.evaluate(()=>window.appUnderTest.battle.paused=false);await page.waitForFunction(()=>window.appUnderTest.battle.entities[1].knockdown?.phase==='down');
 const down=await page.evaluate(async()=>{const app=window.appUnderTest,b=app.battle;b.paused=true;const [u,v]=b.entities,p={id:'down-hit',weapon:'sword',attackStats:u.stats,normal:true,coefficient:1,charge:0,finisher:true,exhausted:false,cPaid:new Set(),statusPaid:new Set(),freezeBoost:new Set()},lp=v.lp,damage=b.hit(u,v,p);app.renderer.render(b,1/60,b.time);const {Vector3}=await import('/vendor/three.module.min.js'),ref=app.renderer.robots.get(v.id);return {damage,sameLP:v.lp===lp,cPaid:p.cPaid.size,phase:v.knockdown.phase,down:v.down,height:v.y,up:new Vector3(0,1,0).applyQuaternion(ref.root.quaternion).y,canAttack:b.attack(v),canJump:b.jump(v)};});assert(down.sameLP&&down.damage===0&&down.cPaid===0&&down.down>0&&down.height===0&&Math.abs(down.up)<1e-7&&!down.canAttack&&!down.canJump);await page.screenshot({path:'charge-artifacts/stagger-sword-down.png'});
 await page.evaluate(()=>window.appUnderTest.battle.paused=false);await page.waitForFunction(()=>{const k=window.appUnderTest.battle.entities[1].knockdown;return k?.phase==='rise'&&k.elapsed>=.22;});
 const rise=await page.evaluate(async()=>{const app=window.appUnderTest,b=app.battle;b.paused=true;const [u,v]=b.entities,p={id:'rise-hit',weapon:'sword',attackStats:u.stats,normal:true,coefficient:1,charge:0,finisher:true,exhausted:false,cPaid:new Set(),statusPaid:new Set(),freezeBoost:new Set()},lp=v.lp,damage=b.hit(u,v,p);app.renderer.render(b,1/60,b.time);const {Vector3}=await import('/vendor/three.module.min.js'),ref=app.renderer.robots.get(v.id);return {damage,sameLP:v.lp===lp,cPaid:p.cPaid.size,phase:v.knockdown.phase,rise:v.rise,up:new Vector3(0,1,0).applyQuaternion(ref.root.quaternion).y,canAttack:b.attack(v),canJump:b.jump(v)};});assert(rise.sameLP&&rise.damage===0&&rise.cPaid===0&&rise.rise>0&&rise.up>0&&rise.up<1&&!rise.canAttack&&!rise.canJump);await page.screenshot({path:'charge-artifacts/stagger-sword-rise.png'});
 await page.evaluate(()=>window.appUnderTest.battle.paused=false);await page.waitForFunction(()=>!window.appUnderTest.battle.entities[1].knockdown);
 const recovered=await page.evaluate(async()=>{const app=window.appUnderTest,b=app.battle;b.paused=true;const [u,v]=b.entities;app.renderer.render(b,1/60,b.time);const {Vector3}=await import('/vendor/three.module.min.js'),ref=app.renderer.robots.get(v.id);const up=new Vector3(0,1,0).applyQuaternion(ref.root.quaternion).y;const p={id:'standing-hit',weapon:'sword',attackStats:u.stats,normal:true,coefficient:1,charge:0,finisher:false,exhausted:false,cPaid:new Set(),statusPaid:new Set(),freezeBoost:new Set()};return {up,damage:b.hit(u,v,p),canAttack:b.attack(v),events:window.downReview,fault:app.frameError};});assert(recovered.damage>0&&recovered.canAttack&&Math.abs(recovered.up-1)<1e-8&&!recovered.fault);const [landed,stood,complete]=recovered.events;assert.equal(landed.type,'down');assert.equal(stood.type,'rise');assert.equal(complete.type,'recovered');assert(Math.abs(stood.time-landed.time-1)<.017);assert(Math.abs(complete.time-stood.time-.5)<.017);await page.screenshot({path:'charge-artifacts/stagger-sword-recovered.png'});
 assert.deepEqual(errors,[]);console.log('Combo stagger browser passed:',JSON.stringify({cuts,linked,airborne,down,rise,recovered}));
}catch(error){console.error(error);process.exitCode=1;}finally{await browser?.close();server.kill();}})();
