import {CATALOG,WEAPONS,FRAMES,PARTS,PASSIVES,SPECIALS} from './data.js';
import {pack,validateGrid} from './grid.js';
export const clone=value=>structuredClone(value);
export function itemLookup(inventory=[]){const loot=new Map(inventory.map(e=>[e.item.id,e.item]));return id=>CATALOG[id]||loot.get(id);}
export function defaultConfig(index=0,enemy=false){
 const frame=enemy?['knight','strider','panzer'][index%3]:['knight','strider','wild'][index%3];const a=enemy?['sword','assault','missile'][index%3]:['sword','dualSword','lance'][index%3],b=enemy?['pistol','dagger','hammer'][index%3]:['pistol','machinegun','sniper'][index%3];
 const coreIds=['cpu:general','memory:standard','motor:standard','battery:standard'];
 return {name:enemy?`敵機 ${index+1}`:`機体 ${String(index+1).padStart(2,'0')}`,armor:Object.fromEntries(PARTS.map(p=>[p,`armor:${frame}:${p}`])),sets:[a,b].map(kind=>({item:`weapon:${kind}`,shield:WEAPONS[kind].shield?'shield:basic':null,separate:false})),placements:pack(coreIds.map(id=>CATALOG[id])),passives:['critical','tension','recharge','extend','drop'],abilities:[`${a}:normal`,`${a}:tech`,`${a}:buff`,`${a}:super`],style:enemy?['aggressive','ranged','ranged'][index%3]:['hybrid','mobile','counter'][index%3],difficulty:'normal'};
}
export function memorySlots(config,getItem){const m=config.placements.map(p=>getItem(p.item)).find(i=>i?.category==='memory');return {normal:m?.normalSlots||0,super:m?.superSlots||0};}
export function aggregate(config,getItem,activeSet=0){
 let lp=0,df=0,armorWeight=0;const resists={},aux={};
 for(const part of PARTS){const i=getItem(config.armor[part]);if(!i)continue;lp+=i.lp;df+=i.df;armorWeight+=i.weight;for(const [k,v]of Object.entries(i.resists||{}))resists[k]=(resists[k]||0)+v;}
 let output=0,burn=0,capacity=0,cpu=null,memory=null,attackCut=0;
 for(const p of config.placements){const i=getItem(p.item);if(!i)continue;if(i.category==='motor'){output+=i.output;burn+=i.burn;}else if(i.category==='battery')capacity+=i.capacity;else if(i.category==='cpu')cpu=i;else if(i.category==='memory')memory=i;else if(i.category==='aux'){aux[i.effect]=(aux[i.effect]||0)+i.value;attackCut+=i.attackValue||0;}}
 for(const [k,v]of Object.entries(aux))if(k.startsWith('res_'))resists[k.slice(4)]=(resists[k.slice(4)]||0)+v;
 const set=config.sets[activeSet],item=getItem(set.item),w=WEAPONS[item?.kind]||WEAPONS.sword,shield=w.shield&&!!getItem(set.shield);
 const weight=armorWeight+(item?.weight||0)+(shield?getItem(set.shield).weight:0),legs=FRAMES[getItem(config.armor.legs)?.frame]||FRAMES.knight;
 const factor=Math.max(.55,1-.4*Math.max(0,weight/legs.limit-1));const passives=new Set(config.passives);
 const cpuApplies=cpu&&(cpu.scope==='all'||cpu.scope===w.id||cpu.scope==='ranged'&&w.ranged||cpu.scope==='melee'&&!w.ranged);
 const at=(item?.at||w.at)*(1+(cpuApplies?cpu.bonus:0))*(1+(aux.at||0));
 const jumps=legs.jumps-(w.heavy&&!['brawler','panzer'].includes(getItem(config.armor.legs)?.frame)?1:0);
 return {lp:Math.round(lp*(1+(aux.lp||0))),df:df*(1+(aux.df||0)),weight,armorWeight,output:output*(1+(aux.c||0)),burn:burn*Math.max(0,1-(aux.burn||0)),capacity:capacity*(1+(aux.bp||0)),aux,resists,at,item,weapon:w,shield,legs,frame:getItem(config.armor.legs)?.frame||'knight',move:legs.move*factor,dash:legs.dash*factor,airDash:legs.airDash*factor,jump:legs.jump*factor,jumps,airDashes:legs.airDashes,weightFactor:factor,crit:Math.min(1,w.crit*(passives.has('critical')?2:1)),regen:25*(1+(aux.regen||0)),regenDelay:passives.has('tension')?.4:.8,attackCut,memory,passives};
}
export function setWeapon(config,slot,id,getItem){const item=getItem(id);if(item?.category!=='weapon')return;config.sets[slot].item=id;if(!WEAPONS[item.kind].shield)config.sets[slot].shield=null;const kinds=new Set(config.sets.map(s=>getItem(s.item)?.kind));config.abilities=config.abilities.filter(id=>kinds.has(SPECIALS[id]?.weapon));}
export function autoAbilities(config,getItem){const slots=memorySlots(config,getItem),kinds=[...new Set(config.sets.map(s=>getItem(s.item)?.kind).filter(Boolean))];const result=[];for(const kind of ['normal','buff','tech'])for(const w of kinds)if(result.filter(id=>SPECIALS[id].kind!=='super').length<slots.normal)result.push(`${w}:${kind}`);for(const w of kinds)if(result.filter(id=>SPECIALS[id].kind==='super').length<slots.super)result.push(`${w}:super`);config.abilities=result;}
export function validateConfig(config,getItem){const errors=validateGrid(config.placements,getItem);for(const p of PARTS)if(getItem(config.armor[p])?.part!==p)errors.push(`${p}の装甲が不正です`);if(config.sets.length!==2)errors.push('武器セットは2個必要です');for(const [n,s]of config.sets.entries()){const i=getItem(s.item);if(i?.category!=='weapon'){errors.push(`セット${n+1}の武器がありません`);continue;}if(s.shield&&!WEAPONS[i.kind].shield)errors.push(`セット${n+1}は盾に対応していません`);}
 if(config.passives.length>5||new Set(config.passives).size!==config.passives.length||config.passives.some(id=>!PASSIVES[id]))errors.push('スキルは重複なしで最大5個です');const m=memorySlots(config,getItem),abilities=config.abilities.map(id=>SPECIALS[id]);if(abilities.some(x=>!x))errors.push('必殺技が見つかりません');if(abilities.filter(x=>x?.kind!=='super').length>m.normal||abilities.filter(x=>x?.kind==='super').length>m.super)errors.push('必殺技がメモリ枠を超えています');if(new Set(config.abilities).size!==config.abilities.length)errors.push('必殺技が重複しています');return errors;}
export function requirements(config){const counts={};function add(id){if(id&&!CATALOG[id])counts[id]=(counts[id]||0)+1;}for(const id of Object.values(config.armor))add(id);const keys=new Set();for(const [n,s]of config.sets.entries()){for(const id of [s.item,s.shield]){const key=`${id}:${s.separate?n:'shared'}`;if(!keys.has(key)){keys.add(key);add(id);}}}for(const p of config.placements)add(p.item);return counts;}
export function validateTeam(configs,inventory){const getItem=itemLookup(inventory),errors=[];const counts={};for(const c of configs){for(const e of validateConfig(c,getItem))errors.push(`${c.name}: ${e}`);for(const [id,n]of Object.entries(requirements(c)))counts[id]=(counts[id]||0)+n;}for(const [id,n]of Object.entries(counts)){const e=inventory.find(x=>x.item.id===id);if(!e||e.count<n)errors.push(`${getItem(id)?.name||'パーツ'}: 必要${n}個／所持${e?.count||0}個`);}return errors;}
export function cost(stats,action,base){const cut=action==='attack'?stats.attackCut:(stats.aux.generic||0)+(stats.aux[action]||0);return base*Math.max(0,1-cut);}
