export class Controls{
 constructor(canvas,onLook){this.keys=new Set();this.pressed=new Set();this.mouseAttack=false;this.mouseGuard=false;this.mode='menu';this.prevButtons=[];this.padName=null;this.touch={x:0,z:0,attack:false,guard:false};this.touchPressed=new Set();this.onLook=onLook;
  window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(!this.keys.has(e.code))this.pressed.add(e.code);this.keys.add(e.code);if(this.mode==='battle'&&['Space','Tab','ShiftLeft','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.clear());
  canvas.addEventListener('pointerdown',e=>{if(this.mode!=='battle')return;if(e.pointerType==='touch')return;if(e.button===0){this.mouseAttack=true;if(!document.pointerLockElement)canvas.requestPointerLock?.().catch?.(()=>{});}if(e.button===2)this.mouseGuard=true;});window.addEventListener('pointerup',e=>{if(e.button===0)this.mouseAttack=false;if(e.button===2)this.mouseGuard=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas)onLook(e.movementX,e.movementY);});
 }
 clear(){this.keys.clear();this.pressed.clear();this.mouseAttack=false;this.mouseGuard=false;this.touch={x:0,z:0,attack:false,guard:false};this.touchPressed.clear();}
 setMode(mode){this.mode=mode;this.clear();if(mode!=='battle'&&document.pointerLockElement)document.exitPointerLock();}
 poll(dt){const pad=Array.from(navigator.getGamepads?.()||[]).find(p=>p?.connected),buttons=pad?pad.buttons.map(b=>b.pressed):[],edge=n=>buttons[n]&&!this.prevButtons[n],axis=n=>Math.abs(pad?.axes[n]||0)>.15?pad.axes[n]:0;this.padName=pad?.id||null;
  const x=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0)+axis(0)+this.touch.x,z=(this.keys.has('KeyW')?1:0)-(this.keys.has('KeyS')?1:0)-axis(1)+this.touch.z,d=Math.max(1,Math.hypot(x,z));if(pad&&this.mode==='battle')this.onLook(axis(2)*dt*900,axis(3)*dt*650);
  const key=c=>this.pressed.has(c),tap=c=>this.touchPressed.has(c);const result={x:x/d,z:z/d,attack:this.mouseAttack||!!buttons[3]||this.touch.attack,guard:this.mouseGuard||!!buttons[4]||this.touch.guard,jumpPressed:key('Space')||edge(1)||tap('jump'),dashPressed:key('ShiftLeft')||key('ShiftRight')||edge(0)||tap('dash'),switchPressed:key('KeyQ')||edge(12)||tap('switch'),lockPressed:key('Tab')||edge(13)||tap('lock'),targetPrevPressed:key('KeyZ')||edge(14),targetNextPressed:key('KeyC')||edge(15),resetPressed:key('KeyR')||edge(2),menuPressed:key('KeyE')||edge(5)||tap('menu'),pausePressed:key('Escape')||edge(9)||tap('pause'),confirmPressed:edge(3)||key('Enter'),cancelPressed:edge(1)||key('Escape'),upPressed:edge(12)||key('ArrowUp'),downPressed:edge(13)||key('ArrowDown')};this.pressed.clear();this.touchPressed.clear();this.prevButtons=buttons;return result;
 }
 bindTouch(root){const stick=root.querySelector('[data-stick]');if(stick){const update=e=>{const r=stick.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width*.35),z=-(e.clientY-r.top-r.height/2)/(r.height*.35),d=Math.max(1,Math.hypot(x,z));this.touch.x=x/d;this.touch.z=z/d;stick.style.setProperty('--jx',`${this.touch.x*25}px`);stick.style.setProperty('--jy',`${-this.touch.z*25}px`);};stick.addEventListener('pointerdown',e=>{stick.setPointerCapture(e.pointerId);update(e);});stick.addEventListener('pointermove',e=>{if(stick.hasPointerCapture(e.pointerId))update(e);});for(const event of ['pointerup','pointercancel'])stick.addEventListener(event,()=>{this.touch.x=0;this.touch.z=0;stick.style.setProperty('--jx','0px');stick.style.setProperty('--jy','0px');});}
  root.querySelectorAll('[data-control]').forEach(el=>{const control=el.dataset.control;el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);if(['attack','guard'].includes(control))this.touch[control]=true;else this.touchPressed.add(control);});for(const event of ['pointerup','pointercancel'])el.addEventListener(event,()=>{if(['attack','guard'].includes(control))this.touch[control]=false;});});}
}
