import {CATALOG,WEAPONS,FRAMES,PARTS,STATUS} from './data.js';
import {randomShape,canonicalShape} from './grid.js';
const pick=(a,rng)=>a[Math.min(a.length-1,Math.floor(rng()*a.length))];
const between=(a,b,rng)=>a+(b-a)*rng();
const round=(n,d=0)=>Number(n.toFixed(d));
const weighted=(rows,rng)=>{let r=rng()*rows.reduce((s,x)=>s+x[1],0);for(const [value,w]of rows){r-=w;if(r<0)return value;}return rows.at(-1)[0];};
export function itemSignature(item){const x={...item};delete x.id;delete x.name;delete x.basic;if(x.shape)x.shape=canonicalShape(x.shape);return JSON.stringify(Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))));}
export function addRewards(inventory,items){const map=new Map(inventory.map(e=>[itemSignature(e.item),e]));const added=[];for(const item of items){const sig=itemSignature(item);let entry=map.get(sig);if(!entry){entry={item:{...item,id:`loot:${globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`}`},count:0,favorite:false,new:true};inventory.push(entry);map.set(sig,entry);}entry.count++;entry.new=true;const existing=added.find(e=>e.item.id===entry.item.id);if(existing)existing.count++;else added.push({item:entry.item,count:1});}return added;}
export function generateCore(level,rng=Math.random){const category=weighted([['cpu',15],['memory',15],['motor',15],['battery',15],['aux',40]],rng);const source=pick(Object.values(CATALOG).filter(i=>i.category===category),rng);const item=structuredClone(source);item.basic=false;
 if(category!=='aux'){for(let i=0;i<100;i++){const shape=randomShape(source.shape.length,rng);if(canonicalShape(shape)!==canonicalShape(source.shape)){item.shape=shape;break;}}item.name=`${source.name}・形状違い`;item.tendency='形状違い';}
 else {const chance=rng();let size=source.shape.length;const li=Math.max(0,Math.min(2,level-1));if(source.tier===2){const [normal,compact]=[[.85,.14],[.7,.25],[.55,.35]][li];size=chance<normal?4:chance<normal+compact?3:2;}else if(source.tier===1)size=chance<[.95,.85,.75][li]?2:1;
 item.shape=size===4?[[0,0],[1,0],[2,0],[1,1]]:size===3?[[0,0],[0,1],[1,1]]:size===2?[[0,0],[1,0]]:[[0,0]];item.tendency=size<source.shape.length?(size===source.shape.length-1?'コンパクト':'高密度'):'標準';item.name=`${source.name}${size<source.shape.length?`・${size}マス`:''}`;}
 return item;
}
export function generateWeapon(rng=Math.random,enemy=null){const kind=enemy?.sets?.length&&rng()<.7?pick(enemy.sets.map(s=>s.kind).filter(Boolean),rng):pick(Object.keys(WEAPONS),rng);const source=CATALOG[`weapon:${kind||'sword'}`],item={...structuredClone(source),basic:false};const tendency=pick(['標準','高威力','軽量','高速'],rng);item.tendency=tendency;
 const t={標準:[1,1.1,1,1,1,1],高威力:[1.15,1.25,1.2,1.3,1,1],軽量:[.95,1.05,.7,.8,1,1],高速:[.9,1,1,1,.85,.9]}[tendency];item.at=round(source.at*between(t[0],t[1],rng));item.weight=round(source.weight*between(t[2],t[3],rng),1);item.interval=round(source.interval*between(t[4],t[5],rng),3);item.element=weighted([['none',50],['fire',12.5],['water',12.5],['lightning',12.5],['light',12.5]],rng);item.status=weighted([[null,75],['oh',10],['freeze',5],['stun',10]],rng);if(item.status)item.at=round(item.at*.9);item.name=`${tendency} ${source.name}`;return item;
}
export function generateArmor(rng=Math.random,enemy=null){const frame=enemy?.frames?.length&&rng()<.7?pick(enemy.frames,rng):pick(Object.keys(FRAMES),rng),part=pick(PARTS,rng),source=CATALOG[`armor:${frame||'knight'}:${part}`],item={...structuredClone(source),basic:false,resists:{}};const tendency=pick(['標準','耐久','防御','軽量'],rng);const t={標準:[1,1.1,1,1.1,1,1],耐久:[1.2,1.3,1,1,1.15,1.25],防御:[1,1,1.2,1.3,1.15,1.25],軽量:[.9,.95,.9,.95,.75,.85]}[tendency];item.lp=round(source.lp*between(t[0],t[1],rng));item.df=round(source.df*between(t[2],t[3],rng),1);item.weight=round(source.weight*between(t[4],t[5],rng),1);const types=['slash','pierce','impact','fire','water','lightning','light','oh','freeze','stun'],up=pick(types,rng),down=pick(types.filter(t=>t!==up),rng);item.resists[up]=pick([.03,.04,.05],rng);item.resists[down]=-pick([.02,.03],rng);item.tendency=tendency;item.name=`${tendency} ${source.name}`;return item;}
function gear(rng,enemy){const type=weighted([['weapon',45],['armor',45],['shield',10]],rng);if(type==='weapon')return generateWeapon(rng,enemy);if(type==='armor')return generateArmor(rng,enemy);return {...structuredClone(CATALOG['shield:basic']),name:'ドロップシールド',basic:false};}
export function rewardCounts(enemyKills,won,collectors=0,training=false){if(training)return {core:0,gear:0,base:0,multiplier:1,extra:0,total:0};const core=3+3*enemyKills+(won?3:0),equipment=3+enemyKills+(won?1:0),base=core+equipment,multiplier=1+collectors;return {core,gear:equipment,base,multiplier,extra:base*collectors,total:base*multiplier};}
export function generateRewards({defeated=[],won=false,collectors=0,level=2,training=false},rng=Math.random){if(training)return [];const result=[];for(let batch=0;batch<=collectors;batch++){for(let i=0;i<3;i++)result.push(generateCore(level,rng));result.push(generateArmor(rng),generateArmor(rng));result.push(rng()<.9?generateWeapon(rng):{...structuredClone(CATALOG['shield:basic']),basic:false,name:'ドロップシールド'});for(const enemy of defeated){for(let i=0;i<3;i++)result.push(generateCore(enemy.level||level,rng));result.push(gear(rng,enemy));}if(won){for(let i=0;i<3;i++)result.push(generateCore(level,rng));result.push(gear(rng));}}return result;}
export function statusChance(item,stats,rolls=1){if(!item.status)return 0;const type=item.status,base=STATUS[type].rate*WEAPONS[item.kind].interval/rolls;return Math.min(1,base*(1+(stats.passives.has('status')?.4:0)+(stats.aux[type]||0))*Math.max(0,1-(stats.resists[type]||0)));}
