import {WEAPONS,SPECIALS,STAGES,DIFFICULTIES,STATUS} from './data.js';
import {aggregate,cost,clone} from './customize.js';
import {contactPhase} from './motion.js';
const TAU=Math.PI*2,GRAVITY=18,RADIUS=.28;
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const angle=(a,b)=>Math.atan2(b.x-a.x,b.z-a.z);
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const lerp=(a,b,t)=>a+(b-a)*t;
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Math.random()}`;
function normalized(x,y,z){const d=Math.hypot(x,y,z)||1;return {x:x/d,y:y/d,z:z/d};}
export function segmentBox(a,b,box){let lo=0,hi=1;for(const [axis,min,max]of [['x',box.x-box.w/2,box.x+box.w/2],['y',0,box.h],['z',box.z-box.d/2,box.z+box.d/2]]){const delta=b[axis]-a[axis];if(Math.abs(delta)<1e-9){if(a[axis]<min||a[axis]>max)return null;continue;}let t1=(min-a[axis])/delta,t2=(max-a[axis])/delta;if(t1>t2)[t1,t2]=[t2,t1];lo=Math.max(lo,t1);hi=Math.min(hi,t2);if(lo>hi)return null;}return lo;}
function segmentSphere(a,b,c,r){const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,fx=a.x-c.x,fy=a.y-c.y,fz=a.z-c.z,A=dx*dx+dy*dy+dz*dz,B=2*(fx*dx+fy*dy+fz*dz),C=fx*fx+fy*fy+fz*fz-r*r;if(C<=0)return 0;if(A<1e-12)return null;const discr=B*B-4*A*C;if(discr<0)return null;const t=(-B-Math.sqrt(discr))/(2*A);return t>=0&&t<=1?t:null;}
export function rampHeight(r,x,z){if(Math.abs(x-r.x)>r.w/2||Math.abs(z-r.z)>r.d/2)return null;return clamp(.5+(z-r.z)/r.d*r.direction,0,1)*r.h;}
export function lineClear(stage,a,b){return !stage.obstacles.some(o=>{const t=segmentBox(a,b,o);if(t===null||t>=.999)return false;if(t>.001)return true;const p={x:lerp(a.x,b.x,.002),y:lerp(a.y,b.y,.002),z:lerp(a.z,b.z,.002)};return Math.abs(p.x-o.x)<o.w/2-1e-6&&Math.abs(p.z-o.z)<o.d/2-1e-6&&p.y>0&&p.y<o.h;})&&!stage.ramps.some(r=>{const t=segmentBox(a,b,r);if(t===null)return false;for(let i=0;i<=16;i++){const k=i/16,p={x:lerp(a.x,b.x,k),y:lerp(a.y,b.y,k),z:lerp(a.z,b.z,k)},h=rampHeight(r,p.x,p.z);if(h!==null&&p.y<h-.015)return true;}return false;});}
function visible(stage,a,b){return lineClear(stage,{x:a.x,y:a.y+.65,z:a.z},{x:b.x,y:b.y+.55,z:b.z});}
export function lockRange(stats){const range=stats.weapon.range*(stats.passives.has('longRange')?1.5:1);return stats.weapon.ranged?Math.max(20,range):20;}
export function weaponRuntimeKey(set,index){return `${set.item}:${set.separate?index:'shared'}`;}
export function damageValue(at,coefficient,df,crit=false){return at*coefficient*100/(100+Math.max(0,df))*(crit?1.5:1);}
export class Battle{
 constructor({allies,enemies,setup,getItem,rng=Math.random}){
  this.getItem=getItem;this.rng=rng;this.setup=clone(setup);this.stage=STAGES[setup.stage];this.time=0;this.countdown=3;this.paused=false;this.finished=false;this.result=null;this.entities=[];this.projectiles=[];this.events=[];this.scheduled=[];this.hitGroups=new Map();this.serial=0;this.training={infinite:false,invulnerable:false,freezeAI:false};
  const playerIndex=clamp(setup.player,0,allies.length-1);for(const [team,configs]of [[0,allies],[1,enemies]])for(const [i,c]of configs.entries()){const offsets=configs.length===1?[0]:configs.length===2?[-1.5,1.5]:[-3,0,3],stats=aggregate(c,getItem);const runtime={};for(const [n,s]of c.sets.entries()){const key=weaponRuntimeKey(s,n);if(!runtime[key]){const w=WEAPONS[getItem(s.item).kind];runtime[key]={ammo:w.clip,reload:0,reloadPending:0,cooldown:0,skillCooldowns:{}};}}
   this.entities.push({id:`${team}:${i}`,team,index:i,config:clone(c),stats,sets:runtime,active:0,x:(team===0?-1:1)*this.stage.spawn,z:offsets[i],y:0,vy:0,vx:0,vz:0,yaw:team===0?Math.PI/2:-Math.PI/2,lp:stats.lp,tension:100,bp:stats.capacity,c:0,regenWait:0,exhausted:false,jumpsUsed:0,airDashesUsed:0,grounded:true,dashTime:0,dashX:0,dashZ:0,switchTime:0,switchQueued:false,attack:null,motion:null,queuedAttack:null,combo:0,comboWindow:0,charge:0,charging:false,guard:false,guardDur:stats.shield?100:60,guardDelay:0,guardBreak:0,status:null,statusTime:0,statusImmune:0,down:0,rise:0,stun:0,controlLoss:0,freeTime:0,buff:null,buffTime:0,target:null,lockOcclusion:0,dead:false,human:team===0&&i===playerIndex,aiDelay:0,aiObservation:null,aiPlan:{x:0,z:0,attack:false},history:[],dealt:0,received:0,kills:0,actionTime:0,lastAttackHeld:false,burstAction:null,hitFlash:0});
  }
  this.human=this.entities.find(u=>u.human);this.observed=this.human;this.collectors=allies.filter(c=>c.passives.includes('drop')).length;
 }
 event(type,data={}){this.events.push({type,...data,time:this.time});}
 consumeEvents(){return this.events.splice(0);}
 runtime(u){return u.sets[weaponRuntimeKey(u.config.sets[u.active],u.active)];}
 activeBuff(u){return u.buff&&u.buffTime>0&&u.buff.weapon===u.stats.weapon.id?u.buff:null;}
 refreshStats(u){u.stats=aggregate(u.config,this.getItem,u.active);u.guardDur=Math.min(u.guardDur,u.stats.shield?100:60);}
 enemiesOf(u){return this.entities.filter(v=>v.team!==u.team&&!v.dead);}
 targetOf(u){return this.entities.find(v=>v.id===u.target&&!v.dead);}
 acquireLock(u,ordered=null){const candidates=(ordered||this.enemiesOf(u).sort((a,b)=>distance(u,a)-distance(u,b))).filter(v=>!v.dead&&distance(u,v)<=lockRange(u.stats)&&visible(this.stage,u,v));u.target=candidates[0]?.id||null;u.lockOcclusion=0;return this.targetOf(u);}
 cycleTarget(u,direction=1,ordered=null){const list=(ordered||this.enemiesOf(u)).filter(v=>distance(u,v)<=lockRange(u.stats)&&visible(this.stage,u,v));if(!list.length){u.target=null;return;}const i=list.findIndex(v=>v.id===u.target);u.target=list[(i+direction+list.length)%list.length].id;u.lockOcclusion=0;}
 range(u){let r=u.stats.weapon.range*(u.stats.passives.has('longRange')?1.5:1);const b=this.activeBuff(u);if(b&&['rifle','sniper'].includes(b.weapon))r*=1.25;return r;}
 incapacitated(u){return u.dead||u.statusTime>0||u.down>0||u.stun>0||u.guardBreak>0;}
 spend(u,action,base){let amount=cost(u.stats,action,base);if(this.activeBuff(u)?.weapon==='dagger'&&action!=='attack')amount*=.65;if(u.tension+1e-8<amount)return false;if(amount>0){u.tension=Math.max(0,u.tension-amount);u.regenWait=u.stats.regenDelay;if(u.tension<=1e-8)u.exhausted=true;}return true;}
 jump(u){if(this.incapacitated(u)||u.switchTime>0||u.actionTime>.12)return false;const first=u.grounded;if(!first&&(u.exhausted||u.jumpsUsed>=u.stats.jumps))return false;if(!first&&!this.spend(u,'extraJump',10))return false;u.guard=false;u.grounded=false;u.jumpsUsed=first?1:u.jumpsUsed+1;u.vy=Math.sqrt(2*GRAVITY*u.stats.jump);this.event('jump',{unit:u.id,x:u.x,y:u.y,z:u.z});return true;}
 dash(u,x,z){if(this.incapacitated(u)||u.exhausted||u.switchTime>0||u.dashTime>0||u.actionTime>.12)return false;if(!u.grounded&&u.airDashesUsed>=u.stats.airDashes)return false;const d=Math.hypot(x,z);if(d<.1){x=Math.sin(u.yaw);z=Math.cos(u.yaw);}else{x/=d;z/=d;}if(!this.spend(u,u.grounded?'groundDash':'airDash',u.grounded?18:22))return false;u.guard=false;u.dashTime=u.grounded?.25:.22;u.dashX=x;u.dashZ=z;if(!u.grounded)u.airDashesUsed++;this.event('dash',{unit:u.id,x:u.x,y:u.y,z:u.z});return true;}
 switchWeapon(u){if(this.incapacitated(u)||u.switchTime>0)return false;u.queuedAttack=null;u.motion=null;if(u.attack||u.actionTime>0){u.switchQueued=true;return true;}u.switchTime=.25;u.guard=false;u.charge=0;u.charging=false;u.combo=0;u.comboWindow=0;return true;}
 maxCharge(u){let t=u.stats.weapon.charge;if(u.stats.passives.has('charge'))t*=.5;if(this.activeBuff(u)&&['lance','rifle','sniper'].includes(u.stats.weapon.id))t*=.7;return t;}
 attack(u,charge=0){
  const rt=this.runtime(u),w=u.stats.weapon;if(this.incapacitated(u)||u.switchTime>0||u.attack||u.actionTime>0||rt.cooldown>0||rt.reload>0||rt.reloadPending>0)return false;if(w.ranged&&rt.ammo<=0)return false;
  const wasExhausted=u.exhausted,next=u.comboWindow>0?(u.combo+1)%Math.max(1,w.combo):0,finisher=!w.ranged&&next===w.combo-1;
  let power=lerp(1,w.chargePower,charge),baseCost=w.tension*lerp(1,1.6,charge);if(!w.ranged&&charge===0){if(w.id==='sword')power=[1,1,1.1,1.3][next];else power=finisher?1.35:1;if(finisher)baseCost*=1.4;}
  if(!wasExhausted&&!this.spend(u,'attack',baseCost))return false;
  u.guard=false;u.rise=0;u.combo=next;u.comboWindow=w.interval*1.6+.32;const target=this.targetOf(u);if(target)u.yaw=angle(u,target);
  const buff=this.activeBuff(u),speedFactor=buff&&['sword','rapier','dualSword','knuckle','pistol','machinegun','dualGun'].includes(w.id)?(w.id==='machinegun'||w.id==='dualSword'?.75:.8):1;
  const interval=(u.stats.item.interval||w.interval)*speedFactor*(finisher?1.6:1);rt.cooldown=interval;u.actionTime=w.ranged?Math.min(.16,interval*.35):Math.min(.28,interval*.55);u.charge=0;
  const packet={id:`a${this.serial++}`,owner:u.id,attackStats:u.stats,coefficient:power*(wasExhausted?.7:1),normal:true,charge,finisher,combo:next,exhausted:wasExhausted,hits:new Set(),cPaid:new Set(),statusPaid:new Set(),freezeBoost:new Set(),yaw:u.yaw,weapon:w.id};
  if(w.ranged){rt.ammo--;this.fireVolley(u,packet);if(rt.ammo===0){rt.reloadPending=Math.max(u.actionTime,interval);}}
  else {u.attack={...packet,elapsed:0,duration:Math.max(.16,Math.min(.5,interval*.8)),previous:0,range:w.range*(buff&&['sword','naginata','scythe','knuckle'].includes(w.id)?1.25:1),arc:w.arc*(buff&&['naginata','scythe'].includes(w.id)?1.2:1),thrust:['rapier','lance'].includes(w.id)};if(charge>0||w.id==='lance'&&finisher){u.dashTime=.12;u.dashX=Math.sin(u.yaw);u.dashZ=Math.cos(u.yaw);}}
  u.queuedAttack=null;u.motion={weapon:w.id,combo:next,charge,finisher,elapsed:0,duration:w.ranged?Math.min(.16,interval):u.attack.duration,shot:true};
  this.event('attack',{unit:u.id,weapon:w.id,charge,finisher,combo:next,normal:true});return true;
 }
 fireVolley(u,packet){const w=u.stats.weapon,buff=this.activeBuff(u);let n=w.pellets;if(buff?.weapon==='heavyShotgun')n=10;const target=this.targetOf(u),maxRange=this.range(u),speed=w.speed*(buff?.weapon==='rifle'?1.25:1);let targets=[target];if(w.id==='missile'&&(packet.charge>.95||buff))targets=this.enemiesOf(u).filter(v=>distance(u,v)<=maxRange&&visible(this.stage,u,v)).sort((a,b)=>a.id===u.target?-1:b.id===u.target?1:distance(u,a)-distance(u,b)).slice(0,3);if(!targets.length)targets=[null];
  for(let i=0;i<n;i++){const t=targets.length===3?(i<2?targets[0]:targets[i-1]):targets[i%targets.length];const muzzle={x:u.x+Math.sin(u.yaw)*.38,y:u.y+.68,z:u.z+Math.cos(u.yaw)*.38};let dir={x:Math.sin(u.yaw),y:0,z:Math.cos(u.yaw)};if(t){const lead=clamp(distance(u,t)/speed,0,.5)*.65;dir=normalized(t.x+t.vx*lead-muzzle.x,t.y+.55-muzzle.y,t.z+t.vz*lead-muzzle.z);}
   let spread=['shotgun','heavyShotgun'].includes(w.id)?.13:['machinegun','assault'].includes(w.id)?.018:w.id==='dualGun'?.025:.004;if(packet.charge>0&&['shotgun','heavyShotgun'].includes(w.id))spread*=lerp(1,.5,packet.charge);if(buff&&['machinegun','assault','dualGun','pistol'].includes(w.id))spread*=.5;const a=(this.rng()-.5)*spread*2,vertical=(this.rng()-.5)*spread;dir=normalized(dir.x*Math.cos(a)+dir.z*Math.sin(a),dir.y+vertical,dir.z*Math.cos(a)-dir.x*Math.sin(a));
   const missile=w.id==='missile',bullet={id:`b${this.serial++}`,owner:u.id,team:u.team,x:muzzle.x,y:muzzle.y,z:muzzle.z,vx:dir.x*speed,vy:dir.y*speed,vz:dir.z*speed,speed,range:maxRange,travel:0,life:maxRange/speed+1,kind:w.id,target:t?.id||null,packet,share:1/n,radius:missile?.1:w.id==='bazooka'?.12:.04,blast:w.id==='bazooka'?(packet.charge>.95?2.5:2)*(buff?1.35:1):0,homing:missile?(buff?4.2:2.5):0,visited:new Set(),normal:packet.normal,group:missile?`m${this.serial++}`:packet.id};
   if(missile)bullet.packet={...packet,cPaid:new Set(),statusPaid:new Set(),freezeBoost:new Set()};
   if(!lineClear(this.stage,{x:u.x,y:u.y+.68,z:u.z},muzzle)){if(bullet.blast)this.explode(bullet,{x:u.x,y:u.y+.68,z:u.z});continue;}this.projectiles.push(bullet);
  }
 }
 skillAvailable(u,id){const s=SPECIALS[id];if(!s||s.weapon!==u.stats.weapon.id||!u.config.abilities.includes(id))return '未装備';if(this.incapacitated(u)||u.switchTime>0)return '行動できません';if(u.attack||u.actionTime>0)return '攻撃動作中';if(u.c<s.cost)return 'Cゲージ不足';if((this.runtime(u).skillCooldowns[id]||0)>0)return '再使用待ち';return null;}
 useSkill(u,id,{fb=false}={}){const s=SPECIALS[id];if(this.skillAvailable(u,id))return false;const rt=this.runtime(u);u.c-=s.cost;rt.skillCooldowns[id]=s.cooldown*(u.stats.passives.has('recharge')?.5:1);u.guard=false;u.rise=0;u.charging=false;u.charge=0;u.queuedAttack=null;u.motion=null;u.combo=0;const target=this.targetOf(u);if(target)u.yaw=angle(u,target);
  if(s.kind==='buff'){u.buff=s;u.buffTime=s.duration*(u.stats.passives.has('extend')?1.5:1);u.actionTime=.15;this.event('buff',{unit:u.id,name:s.name,duration:u.buffTime});return true;}
  const coeff=s.kind==='normal'?3:s.kind==='tech'?5:10,w=u.stats.weapon,budget=100*coeff*(u.stats.at/w.at),packet={id:`s${this.serial++}`,owner:u.id,attackStats:u.stats,normal:false,coefficient:1,budget,charge:0,finisher:!w.ranged,exhausted:false,hits:new Set(),cPaid:new Set(),statusPaid:new Set(),freezeBoost:new Set(),yaw:u.yaw,weapon:w.id,skill:s.kind,fb:fb&&!w.ranged,fbTarget:fb?target?.id:null,fbDone:false};
  this.event('special',{unit:u.id,name:s.name,kind:s.kind});const delay=s.kind==='super'?.5:.16;
  if(w.ranged){const volleys=s.kind==='super'?(['machinegun','assault','dualGun'].includes(w.id)?16:4):s.kind==='tech'?(['machinegun','assault'].includes(w.id)?12:['pistol','dualGun'].includes(w.id)?3:2):(['machinegun','assault','dualGun'].includes(w.id)?6:1);const spacing=s.kind==='super'?.06:.075;u.actionTime=delay+volleys*spacing+.15;
   for(let i=0;i<volleys;i++)this.schedule(delay+i*spacing,()=>{if(u.dead||this.incapacitated(u))return;const p={...packet,id:`${packet.id}:${i}`,budget:budget/volleys,hits:new Set(),cPaid:new Set(),statusPaid:new Set(),freezeBoost:new Set(),status:s.kind==='tech'&&w.id==='heavyShotgun'?'stun':s.kind==='tech'&&w.id==='bazooka'?'oh':null};const oldYaw=u.yaw;if(w.id==='dualGun'&&s.kind==='tech')u.yaw+=Math.sin(i*2)*.3;this.fireVolley(u,p);u.motion={weapon:w.id,combo:i,elapsed:0,duration:.12,shot:true};u.yaw=oldYaw;if((w.id==='rifle'||w.id==='sniper')&&s.kind==='tech')for(const b of this.projectiles.filter(b=>b.packet===p))b.pierce=true;if(w.id==='bazooka'&&s.kind!=='normal')for(const b of this.projectiles.filter(b=>b.packet===p))b.blast*=1.5;});
  }else {const wide=s.kind==='tech'&&['sword','dualSword','naginata','hammer','scythe'].includes(w.id)||s.kind==='super'&&['naginata','scythe','dualSword'].includes(w.id),range=w.range+(s.kind==='super'?1.5:s.kind==='tech'?.8:.4);u.actionTime=delay+.45;u.attack={...packet,elapsed:-delay,duration:.45,previous:-delay,range,arc:wide?360:w.arc,thrust:['rapier','lance'].includes(w.id),status:s.kind==='tech'&&w.id==='rapier'?'stun':s.kind==='tech'&&w.id==='knuckle'?'stun':s.kind==='tech'&&w.id==='hammer'?'oh':null};if(['sword','lance','rapier','dagger','knuckle'].includes(w.id)){u.dashTime=.2;u.dashX=Math.sin(u.yaw);u.dashZ=Math.cos(u.yaw);} }
  return true;
 }
 schedule(delay,fn){this.scheduled.push({at:this.time+delay,fn});}
 groundAt(x,z){let h=0;for(const o of this.stage.obstacles)if(Math.abs(x-o.x)<=o.w/2&&Math.abs(z-o.z)<=o.d/2)h=Math.max(h,o.h);for(const r of this.stage.ramps){const rh=rampHeight(r,x,z);if(rh!==null)h=Math.max(h,rh);}return h;}
 blocked(u,x,z){for(const o of this.stage.obstacles)if(u.y<o.h-.05&&Math.abs(x-o.x)<o.w/2+RADIUS&&Math.abs(z-o.z)<o.d/2+RADIUS){const rh=this.stage.ramps.map(r=>rampHeight(r,x,z)).filter(v=>v!==null);if(!rh.some(h=>Math.abs(h-o.h)<.22))return true;}const h=this.groundAt(x,z);return h>u.y+.22&&u.grounded;}
 move(u,dx,dz,dt){const maxX=this.stage.width/2-RADIUS,maxZ=this.stage.depth/2-RADIUS;const x=clamp(u.x+dx,-maxX,maxX),z=clamp(u.z+dz,-maxZ,maxZ);if(!this.blocked(u,x,u.z))u.x=x;if(!this.blocked(u,u.x,z))u.z=z;const ground=this.groundAt(u.x,u.z);if(u.grounded){if(ground<u.y-.22){u.grounded=false;u.jumpsUsed=Math.max(1,u.jumpsUsed);u.vy=0;}else if(ground<=u.y+.22)u.y=ground;}
  if(!u.grounded){const prev=u.y;u.vy-=GRAVITY*dt;u.y+=u.vy*dt;if(u.y<=ground&&prev>=ground-.12&&u.vy<=0){u.y=ground;u.vy=0;u.grounded=true;u.jumpsUsed=0;u.airDashesUsed=0;}else if(u.y<0){u.y=0;u.vy=0;u.grounded=true;u.jumpsUsed=0;u.airDashesUsed=0;}}
 }
 handleInput(u,input,dt){if(this.incapacitated(u))return;if(input.switchPressed)this.switchWeapon(u);if(input.jumpPressed)this.jump(u);if(input.dashPressed)this.dash(u,input.x||0,input.z||0);if(input.guard){u.queuedAttack=null;if(!u.attack&&u.actionTime<=0&&u.switchTime<=0){u.guard=true;u.charging=false;u.charge=0;}}else u.guard=false;
  const w=u.stats.weapon;if(input.attack&&!u.guard&&!input.guard&&u.switchTime<=0&&!u.switchQueued){if(w.automatic)this.attack(u);else {u.charging=true;u.charge=Math.min(this.maxCharge(u),u.charge+dt);}}if(!input.attack&&u.lastAttackHeld&&u.charging){const charge=u.charge>.15?clamp(u.charge/this.maxCharge(u),0,1):0;if(!this.attack(u,charge)&&!w.ranged&&!input.guard&&!u.switchQueued&&u.switchTime<=0&&this.runtime(u).cooldown<=.22&&(!u.attack||u.attack.duration-u.attack.elapsed<=.22))u.queuedAttack={charge,remaining:.22};u.charging=false;u.charge=0;}
  if(u.queuedAttack&&!input.guard&&!input.attack)this.attack(u,u.queuedAttack.charge);u.lastAttackHeld=!!input.attack;
  const target=this.targetOf(u);if(target){u.yaw+=wrap(angle(u,target)-u.yaw)*Math.min(1,dt*14);}else if(Math.hypot(input.x||0,input.z||0)>.1&&!u.charging&&!input.attack){u.yaw+=wrap(Math.atan2(input.x,input.z)-u.yaw)*Math.min(1,dt*12);}if(u.guard&&!target&&Math.hypot(input.x||0,input.z||0)>.1)u.yaw+=wrap(Math.atan2(input.x,input.z)-u.yaw)*Math.min(1,dt*10);
 }
 updateUnit(u,input,dt){if(u.dead)return;if(u.queuedAttack){u.queuedAttack.remaining-=dt;if(u.queuedAttack.remaining<0)u.queuedAttack=null;}if(u.motion){u.motion.elapsed+=dt;if(u.motion.elapsed>u.motion.duration+.2)u.motion=null;}const wasSwitching=u.switchTime>0;for(const k of ['regenWait','dashTime','switchTime','comboWindow','guardDelay','guardBreak','statusImmune','down','rise','stun','actionTime','hitFlash'])u[k]=Math.max(0,u[k]-dt);
  for(const rt of Object.values(u.sets)){rt.cooldown=Math.max(0,rt.cooldown-dt);for(const key of Object.keys(rt.skillCooldowns))rt.skillCooldowns[key]=Math.max(0,rt.skillCooldowns[key]-dt);if(rt.reloadPending>0){rt.reloadPending=Math.max(0,rt.reloadPending-dt);if(rt.reloadPending===0){const setIndex=u.config.sets.findIndex((s,n)=>u.sets[weaponRuntimeKey(s,n)]===rt),w=WEAPONS[this.getItem(u.config.sets[setIndex].item).kind];rt.reload=w.reload*(this.activeBuff(u)&&['pistol','machinegun'].includes(w.id)?.75:1);}}
   else if(rt.reload>0){rt.reload=Math.max(0,rt.reload-dt);if(rt.reload===0){const s=u.config.sets.find((s,n)=>u.sets[weaponRuntimeKey(s,n)]===rt);rt.ammo=WEAPONS[this.getItem(s.item).kind].clip;}}}
  if(wasSwitching&&u.switchTime===0){u.active=1-u.active;this.refreshStats(u);this.event('switch',{unit:u.id,set:u.active});}if(u.switchQueued&&!u.attack&&u.actionTime===0&&!this.incapacitated(u)){u.switchQueued=false;this.switchWeapon(u);}
  if(u.buffTime>0){u.buffTime=Math.max(0,u.buffTime-dt);if(u.buffTime===0)u.buff=null;}if(u.statusTime>0){u.statusTime=Math.max(0,u.statusTime-dt);if(u.statusTime===0){u.status=null;u.statusImmune=1;}}
  u.bp=Math.max(0,u.bp-u.stats.burn*dt);if(u.regenWait===0){u.tension=Math.min(100,u.tension+u.stats.regen*dt);if(u.tension>=25)u.exhausted=false;}if(!u.guard&&u.guardDelay===0)u.guardDur=Math.min(u.stats.shield?100:60,u.guardDur+20*dt);
  const disabled=this.incapacitated(u);if(disabled){u.queuedAttack=null;u.motion=null;u.controlLoss+=dt;u.freeTime=0;u.guard=false;u.charging=false;u.charge=0;if(u.controlLoss>=12){u.status=null;u.statusTime=0;u.stun=0;u.guardBreak=0;u.down=.35;u.rise=.6;u.statusImmune=1;u.controlLoss=0;this.event('escape',{unit:u.id});}}else {u.freeTime+=dt;if(u.freeTime>=.5)u.controlLoss=0;this.handleInput(u,input,dt);}
  if(u.human){const target=this.targetOf(u);if(u.target&&!target)u.target=null;if(target){if(distance(u,target)>lockRange(u.stats)*1.15)u.target=null;else if(!visible(this.stage,u,target)){u.lockOcclusion+=dt;if(u.lockOcclusion>=1)u.target=null;}else u.lockOcclusion=0;}}
  let vx=0,vz=0;if(!disabled){if(u.dashTime>0){const speed=u.grounded?u.stats.dash:u.stats.airDash;vx=u.dashX*speed;vz=u.dashZ*speed;}else {let speed=u.stats.move*(u.guard?.35:1);const w=u.stats.weapon,stopped=u.grounded&&u.actionTime>0&&(w.id==='sniper'||['bazooka','missile'].includes(w.id)&&u.stats.frame!=='panzer');if(stopped)speed=0;if(w.id==='assault'&&u.actionTime>0&&!this.activeBuff(u))speed*=.85;vx=(input.x||0)*speed;vz=(input.z||0)*speed;}}
  const oldX=u.x,oldZ=u.z;this.move(u,vx*dt,vz*dt,dt);u.vx=(u.x-oldX)/dt;u.vz=(u.z-oldZ)/dt;
  if(u.attack){if(this.incapacitated(u)){u.attack=null;}else {this.meleeStep(u,dt);}}
  u.history.push({time:this.time,x:u.x,y:u.y,z:u.z,vx:u.vx,vz:u.vz,attacking:!!u.attack||u.actionTime>0,guard:u.guard,dead:u.dead});while(u.history.length&&u.history[0].time<this.time-1)u.history.shift();
 }
 meleeStep(u,dt){const a=u.attack;a.previous=a.elapsed;a.elapsed+=dt;if(a.elapsed<0)return;const w=u.stats.weapon,active=a.elapsed>=a.duration*.18&&a.previous<=a.duration*.74;for(const v of this.enemiesOf(u)){if(!active||a.hits.has(v.id)||Math.abs(v.y-u.y)>.9||distance(u,v)>a.range+.35||!visible(this.stage,u,v))continue;let hit=false;if(a.thrust){hit=Math.abs(wrap(angle(u,v)-a.yaw))<Math.max(.15,Math.atan2(.45,distance(u,v)));}else {const arc=a.arc*Math.PI/180,prev=contactPhase({...a,elapsed:a.previous}),curr=contactPhase(a),targetAngle=wrap(angle(u,v)-a.yaw);const margin=Math.atan2(.35,distance(u,v));hit=targetAngle>=-arc/2+arc*prev-margin&&targetAngle<=-arc/2+arc*curr+margin;if(a.arc>=360)hit=true;}
   if(hit){a.hits.add(v.id);this.hit(u,v,a,1);if(a.skill==='tech'&&w.id==='scythe'&&!v.dead){const amount=this.activeBuff(u)?1.5:1;this.move(v,Math.sin(angle(v,u))*amount,Math.cos(angle(v,u))*amount,0);} }
  }
  if(a.elapsed>=a.duration){if(a.fb&&!a.fbDone){u.status='oh';u.statusTime=2;u.guard=false;this.event('fbFail',{unit:u.id});}u.attack=null;}
 }
 statusRoll(u,v,packet,group){if(packet.statusPaid.has(v.id))return;packet.statusPaid.add(v.id);if(v.statusTime>0||v.statusImmune>0||v.down>0||v.rise>0)return;const stats=packet.attackStats||u.stats,type=packet.status||stats.item.status;if(!type)return;const rolls=packet.weapon==='missile'?4:1;let chance=packet.status?(type==='stun'?.15:.1):STATUS[type].rate*WEAPONS[packet.weapon].interval/rolls;chance*=1+(stats.passives.has('status')?.4:0)+(stats.aux[type]||0);if(this.activeBuff(u)?.weapon==='bazooka'&&type==='oh')chance*=1.5;chance*=Math.max(0,1-(v.stats.resists[type]||0));if(this.rng()<Math.min(1,chance)){v.status=type;v.statusTime=STATUS[type].duration;v.guard=false;v.charging=false;this.event('status',{unit:v.id,status:type});}}
 hit(u,v,packet,share=1,position=null,group=packet.id){if(v.dead||v.down>0||v.rise>0)return 0;if(this.setup.training&&this.training.invulnerable&&v.human)return 0;
  const stats=packet.attackStats||u.stats,direction=angle(v,u),guard=v.guard&&Math.abs(wrap(direction-v.yaw))<=Math.PI/3;let df=v.stats.df;if(guard&&v.stats.passives.has('guard'))df*=1.5;const crit=this.rng()<stats.crit;
  let at=packet.normal?stats.at:packet.budget;let power=packet.coefficient*share;if(!packet.normal&&stats.passives.has('special'))power*=1.2;if(stats.passives.has('damage'))power*=1.1;
  const element=stats.item.element||'none',phys=stats.weapon.physical;const physical=Math.max(0,1-(v.stats.resists[phys]||0)),elementRes=Math.max(0,1-(v.stats.resists[element]||0));power*=element==='none'?physical:physical*.7+elementRes*.3;
  if(['shotgun','heavyShotgun'].includes(packet.weapon)){const near=packet.weapon==='shotgun'?3:4,max=this.range(u),d=distance(u,v);power*=lerp(1,.3,clamp((d-near)/(max-near),0,1));if(this.activeBuff(u)?.weapon==='shotgun'&&d<=near)power*=1.2;}
  const hitKey=`${group}:${v.id}`;if(v.status==='freeze'&&v.statusTime>0){v.status=null;v.statusTime=0;v.statusImmune=1;this.hitGroups.set(hitKey,this.time+.2);}if(this.hitGroups.has(hitKey))power*=1.25;
  let damage=damageValue(at,power,df,crit);if(guard){const guardDamage=damage*.3*(this.activeBuff(u)&&['hammer','heavyShotgun'].includes(packet.weapon)?1.5:1);v.guardDur=Math.max(0,v.guardDur-guardDamage);v.guardDelay=1;damage*=v.stats.shield?.3:.6;if(v.guardDur<=0&&!v.stats.passives.has('guardOff')){v.guard=false;v.guardBreak=1.2;v.guardDur=(v.stats.shield?100:60)*.5;this.event('guardBreak',{unit:v.id});}}
  if(v.stats.passives.has('save'))damage*=.9;damage=Math.max(1,Math.round(damage));const actual=Math.min(v.lp,damage);v.lp=Math.max(0,v.lp-actual);u.dealt+=actual;v.received+=actual;v.hitFlash=.12;
  const hitBonus=!packet.cPaid.has(v.id);packet.cPaid.add(v.id);if(packet.normal&&u.bp>0){const aoeAlready=packet.cBonusUsed===true;const hits=packet.weapon==='dualSword'?2:1;u.c=Math.min(500,u.c+((hitBonus&&!aoeAlready?10*hits:0)+actual*.6)*u.stats.output);packet.cBonusUsed=true;}if(v.bp>0)v.c=Math.min(500,v.c+actual*.2*v.stats.output);
  this.event('hit',{unit:v.id,attacker:u.id,x:v.x,y:v.y+.6,z:v.z,damage:actual,crit,guard});
  if(packet.fb&&packet.fbTarget===v.id&&v.lp<=v.stats.lp*.2&&visible(this.stage,u,v)){v.lp=0;packet.fbDone=true;if(u.attack)u.attack.fbDone=true;this.event('fb',{unit:v.id,attacker:u.id});}
  if(v.lp<=0){this.kill(v,u);return actual;}
  if(!guard&&!packet.exhausted){this.react(u,v,packet);this.statusRoll(u,v,packet,group);}return actual;
 }
 react(u,v,p){if(v.statusTime>0)return;const w=p.weapon,buff=this.activeBuff(v);if(buff?.weapon==='hammer'&&(v.attack||v.actionTime>0))return;if(p.skill==='tech'&&w==='knuckle'||w==='knuckle'&&p.finisher){if(v.grounded){v.grounded=false;v.jumpsUsed=Math.max(v.jumpsUsed,1);v.vy=Math.sqrt(2*GRAVITY*1.2);v.stun=.15;}else v.stun=Math.max(v.stun,.1);}
  else if(p.finisher||w==='bazooka'){let force=['hammer','bazooka'].includes(w)?3.4:1.7;if(this.activeBuff(u)&&['hammer','shotgun','heavyShotgun'].includes(w))force*=1.4;this.move(v,Math.sin(u.yaw)*force,Math.cos(u.yaw)*force,0);this.knockDown(v);}
  else if(!['machinegun','assault','dualGun','missile'].includes(w)){v.stun=Math.max(v.stun,w==='sniper'||p.charge>.9?.3:Math.min(.25,u.stats.weapon.interval*.6));v.attack=null;v.actionTime=0;v.charging=false;v.charge=0;}
 }
 knockDown(u){u.status=null;u.statusTime=0;u.stun=0;u.down=.8;u.rise=0;u.guard=false;u.attack=null;u.actionTime=0;u.charging=false;u.charge=0;this.schedule(.8,()=>{if(!u.dead){u.rise=.6;u.statusImmune=1;}});}
 kill(v,u){v.dead=true;v.lp=0;v.attack=null;v.guard=false;v.target=null;u.kills++;this.event('kill',{unit:v.id,attacker:u.id,x:v.x,y:v.y,z:v.z});for(const e of this.entities)if(e.target===v.id)e.target=null;if(v.human){this.observed=this.entities.find(e=>e.team===0&&!e.dead)||v;this.event('spectate',{unit:this.observed.id});}}
 explode(b,pos,direct=null){const u=this.entities.find(u=>u.id===b.owner);if(!u)return;this.event('explosion',{x:pos.x,y:pos.y,z:pos.z,radius:b.blast});for(const v of this.enemiesOf(u)){const d=Math.hypot(v.x-pos.x,v.y+.55-pos.y,v.z-pos.z);if(d>b.blast+.3&&v!==direct)continue;if(v!==direct&&!lineClear(this.stage,{x:pos.x,y:Math.max(.06,pos.y),z:pos.z},{x:v.x,y:v.y+.55,z:v.z}))continue;const factor=v===direct?1:lerp(1,.3,clamp(d/b.blast,0,1));this.hit(u,v,b.packet,b.share*factor,pos,b.group);}}
 projectileStep(b,dt){const u=this.entities.find(u=>u.id===b.owner);if(!u)return false;b.life-=dt;if(b.life<=0||b.travel>=b.range)return false;
  if(b.homing){const t=this.entities.find(u=>u.id===b.target&&!u.dead);if(t){const dir=normalized(t.x-b.x,t.y+.5-b.y,t.z-b.z),current=normalized(b.vx,b.vy,b.vz),blend=clamp(b.homing*dt,0,1),n=normalized(lerp(current.x,dir.x,blend),lerp(current.y,dir.y,blend),lerp(current.z,dir.z,blend));b.vx=n.x*b.speed;b.vy=n.y*b.speed;b.vz=n.z*b.speed;}}
  const a={x:b.x,y:b.y,z:b.z},travel=Math.min(b.speed*dt,b.range-b.travel),factor=travel/b.speed,point={x:b.x+b.vx*factor,y:b.y+b.vy*factor,z:b.z+b.vz*factor};let closest=1.1,hitUnit=null,hitObstacle=false;
  for(const o of this.stage.obstacles){const t=segmentBox(a,point,o);if(t!==null&&t<closest){closest=t;hitUnit=null;hitObstacle=true;}}
  if(!lineClear(this.stage,a,point)&&closest>1){closest=.5;hitObstacle=true;}
  if(point.y<=0&&a.y>0){const t=a.y/(a.y-point.y);if(t<closest){closest=t;hitObstacle=true;hitUnit=null;}}
  for(const v of this.entities){if(v.team===b.team||v.dead||v.down>0||v.rise>0||b.visited.has(v.id))continue;const t=segmentSphere(a,point,{x:v.x,y:v.y+.55,z:v.z},.38+b.radius);if(t!==null&&t<closest){closest=t;hitUnit=v;hitObstacle=false;}}
  b.x=point.x;b.y=point.y;b.z=point.z;b.travel+=travel;
  if(closest<=1){const pos={x:lerp(a.x,point.x,closest),y:lerp(a.y,point.y,closest),z:lerp(a.z,point.z,closest)};if(b.blast)this.explode(b,pos,hitUnit);else if(hitUnit){this.hit(u,hitUnit,b.packet,b.share,pos,b.group);b.visited.add(hitUnit.id);}else this.event('spark',pos);return !!(b.pierce&&hitUnit&&!hitObstacle);}
  if(Math.abs(b.x)>this.stage.width/2||Math.abs(b.z)>this.stage.depth/2)return false;return true;
 }
 selectAITarget(u){const visibleEnemies=this.enemiesOf(u).filter(v=>visible(this.stage,u,v));if(!visibleEnemies.length)return null;const human=this.human,coord=this.setup.coordination;let target=null;if(u.team===0&&coord==='focus'&&!human.dead)target=visibleEnemies.find(v=>v.id===human.target);if(u.team===0&&coord==='support')target=visibleEnemies.sort((a,b)=>distance(a,human)-distance(b,human))[0];if(!target)target=visibleEnemies.sort((a,b)=>{const allies=this.entities.filter(e=>e.team===u.team&&e!==u&&!e.dead),aUsed=allies.filter(e=>e.target===a.id).length,bUsed=allies.filter(e=>e.target===b.id).length;return distance(u,a)+(coord==='spread'?aUsed*4:0)-distance(u,b)-(coord==='spread'?bUsed*4:0);})[0];return target;}
 ai(u,dt){if(this.setup.training&&this.training.freezeAI)return {x:0,z:0,attack:false};const d=DIFFICULTIES[u.config.difficulty],style=u.config.style;u.aiDelay-=dt;if(u.aiDelay<=0){u.aiDelay=lerp(...d.reaction,this.rng());const target=this.selectAITarget(u);if(target){u.target=target.id;const delayed=target.history.findLast(h=>h.time<=this.time-u.aiDelay)||target.history[0];u.aiObservation=delayed?{...delayed,id:target.id}:null;}else {u.target=null;u.aiObservation=null;}}
  const target=this.targetOf(u),obs=u.aiObservation;if(!target||!obs){const foes=this.enemiesOf(u);if(!foes.length)return {x:0,z:0,attack:false};const nearest=foes.sort((a,b)=>distance(u,a)-distance(u,b))[0];let path={x:Math.sign(nearest.x-u.x),z:0};if(this.blocked(u,u.x+path.x*.8,u.z)){path={x:0,z:Math.sign(u.z||1)};}return path;}
  const w=u.stats.weapon,dist=Math.hypot(obs.x-u.x,obs.z-u.z),dx=obs.x-u.x,dz=obs.z-u.z,len=Math.hypot(dx,dz)||1,forward={x:dx/len,z:dz/len};u.yaw+=wrap(Math.atan2(dx,dz)-u.yaw)*Math.min(1,dt*10);
  if((style==='hybrid'||w.ranged&&dist<2.5||!w.ranged&&dist>6)&&d.level>=2){const other=this.getItem(u.config.sets[1-u.active].item),ow=WEAPONS[other.kind];if(w.ranged&&dist<2.5&&!ow.ranged||!w.ranged&&dist>6&&ow.ranged||w.ranged&&this.runtime(u).reload>0&&ow.ranged&&this.setsAvailable(u,1-u.active)){this.switchWeapon(u);}}
  const ideal=w.ranged?Math.min(this.range(u)*.7,w.id==='sniper'?20:w.id.includes('Shotgun')||w.id==='shotgun'?4:12):w.range*.7;let x=0,z=0;
  if(dist>ideal+.5){x=forward.x;z=forward.z;}else if(w.ranged&&dist<ideal-1){x=-forward.x;z=-forward.z;}else if(style==='mobile'||w.ranged){const side=Math.sin(this.time*.8+u.index*2+u.team);x=forward.z*side*.65;z=-forward.x*side*.65;}
  if(this.blocked(u,u.x+x*.7,u.z+z*.7)){const side=u.index%2?1:-1;x=forward.z*side;z=-forward.x*side;if(d.level>=2&&u.grounded&&this.rng()<.015)this.jump(u);}
  const out={x,z,attack:false,guard:false};if(u.tension<25&&!u.exhausted&&d.level>=2){out.x=-forward.x;out.z=-forward.z;return out;}
  if(obs.attacking&&dist<3&&style==='counter'&&u.aiDelay<.08){out.guard=true;if(d.level===3&&this.rng()<.08){out.dashPressed=true;out.x=forward.z;out.z=-forward.x;}return out;}
  if(d.level>=2&&u.aiDelay<.08){const threatening=this.projectiles.find(b=>b.team!==u.team&&Math.hypot(b.x-u.x,b.z-u.z)<2.4&&visible(this.stage,u,{x:b.x,y:Math.max(0,b.y-.5),z:b.z}));if(threatening&&this.rng()<(d.level===3?.7:.35)){out.dashPressed=true;out.x=forward.z;out.z=-forward.x;}}
  if(style==='mobile'&&d.level>=2&&u.aiDelay<.035&&this.rng()<.25){if(u.grounded)out.jumpPressed=true;else if(u.airDashesUsed<u.stats.airDashes)out.dashPressed=true;else if(u.jumpsUsed<u.stats.jumps&&this.rng()<.3)out.jumpPressed=true;}
  const clear=visible(this.stage,u,target);if(clear&&dist<=this.range(u)+(w.ranged?0:.25)&&Math.abs(obs.y-u.y)<(w.ranged?100:1)){const rt=this.runtime(u);if(rt.cooldown===0&&rt.reload===0&&u.actionTime===0&&!u.attack&&!out.guard){if(w.automatic)out.attack=true;else this.attack(u,d.level===3&&['sniper','hammer','rifle'].includes(w.id)&&dist>ideal*.9?.65:0);}}
  if(clear&&d.level>=2&&u.aiDelay<.05&&!this.incapacitated(u)&&!u.attack&&u.actionTime===0){const available=u.config.abilities.map(id=>SPECIALS[id]).filter(s=>s.weapon===w.id&&!this.skillAvailable(u,s.id));let s=available.find(s=>s.kind==='buff'&&(!u.buff||u.buffTime<3)&&dist<Math.max(4,this.range(u)));if(!s)s=available.find(s=>s.kind==='super'&&dist<this.range(u)&&obs.attacking);if(!s)s=available.find(s=>s.kind!=='buff'&&s.kind!=='super'&&dist<this.range(u));if(s)this.useSkill(u,s.id);}
  return out;
 }
 setsAvailable(u,n){const rt=u.sets[weaponRuntimeKey(u.config.sets[n],n)];return rt.reload===0&&rt.ammo>0;}
 tick(dt,humanInput={}){if(this.paused||this.finished)return;dt=clamp(dt,0,.04);if(this.countdown>0){this.countdown=Math.max(0,this.countdown-dt);return;}this.time+=dt;
  const due=this.scheduled.filter(s=>s.at<=this.time);this.scheduled=this.scheduled.filter(s=>s.at>this.time);for(const task of due)task.fn();for(const [k,t]of this.hitGroups)if(t<this.time)this.hitGroups.delete(k);
  for(const u of this.entities){if(u.dead)continue;if(this.setup.training&&this.training.infinite){u.tension=100;u.c=500;u.bp=u.stats.capacity;u.exhausted=false;}this.updateUnit(u,u.human?humanInput:this.ai(u,dt),dt);}
  for(let i=0;i<this.entities.length;i++)for(let j=i+1;j<this.entities.length;j++){const a=this.entities[i],b=this.entities[j];if(a.dead||b.dead||Math.abs(a.y-b.y)>.8)continue;const d=distance(a,b);if(d<.56){const push=(.56-d)*.45,dx=(a.x-b.x)/(d||1),dz=(a.z-b.z)/(d||1);this.move(a,dx*push,dz*push,0);this.move(b,-dx*push,-dz*push,0);}}
  this.projectiles=this.projectiles.filter(b=>this.projectileStep(b,dt));if(!this.setup.training)this.checkEnd();
 }
 checkEnd(){const alive0=this.entities.some(u=>u.team===0&&!u.dead),alive1=this.entities.some(u=>u.team===1&&!u.dead);if(!alive0||!alive1){this.finish(!alive0&&!alive1?'draw':alive0?'win':'loss','撃破');return;}if(this.setup.duration>0&&this.time>=this.setup.duration){const ratios=[0,1].map(team=>{const all=this.entities.filter(u=>u.team===team);return all.reduce((s,u)=>s+u.lp,0)/all.reduce((s,u)=>s+u.stats.lp,0);});this.finish(Math.abs(ratios[0]-ratios[1])<1e-8?'draw':ratios[0]>ratios[1]?'win':'loss','時間切れ');}}
 finish(outcome,reason){if(this.finished)return;this.finished=true;this.result={outcome,reason,time:this.time,collectors:this.collectors,defeated:this.entities.filter(u=>u.team===1&&u.dead).map(u=>({level:DIFFICULTIES[u.config.difficulty].level,sets:u.config.sets.map(s=>({kind:this.getItem(s.item).kind})),frames:Object.values(u.config.armor).map(id=>this.getItem(id).frame)})),level:Math.round(this.entities.filter(u=>u.team===1).reduce((s,u)=>s+DIFFICULTIES[u.config.difficulty].level,0)/this.setup.enemies),units:this.entities.map(u=>({name:u.config.name,team:u.team,lp:u.lp,maxLP:u.stats.lp,dealt:u.dealt,received:u.received,kills:u.kills})),training:this.setup.training};this.event('end',{result:this.result});}
}
